### ISSUE TITLE
Reload in Dev

### ISSUE THREAD

**Issue by chrisdel101** [ShijiMi-Soup/pywebview-with-vite-react#5]
I'm having to stop the app after each change, even just on the frontend. This makes it impossible to work. 
Is this expected? Or I am I just using the wrong script? (npm run start)

**Comment by ShijiMi-Soup** [comment]
Currently hot reload is not supported for `npm run start` because I don't know how to let python recognize the changes made in the frontend. I think it is not supported in the original boilerplate (https://github.com/r0x0r/pywebview-react-boilerplate) either. 
If you are ok with using hot reload only on the frontend (without the backend running), `npm run dev` would work.

**Comment by chrisdel101** [comment]
Okay thanks.
